const menuToggle=document.querySelector('.menu-toggle');
const mobileNav=document.querySelector('#mobile-nav');
menuToggle.addEventListener('click',()=>{const open=menuToggle.getAttribute('aria-expanded')==='true';menuToggle.setAttribute('aria-expanded',String(!open));menuToggle.setAttribute('aria-label',open?'Abrir menu':'Fechar menu');mobileNav.hidden=open;});
mobileNav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{mobileNav.hidden=true;menuToggle.setAttribute('aria-expanded','false');menuToggle.setAttribute('aria-label','Abrir menu');}));
const nowParts=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());
const datePart=type=>Number(nowParts.find(p=>p.type===type).value);
const today=new Date(datePart('year'),datePart('month')-1,datePart('day'));let month=new Date(today.getFullYear(),today.getMonth(),1);let selectedDate=null;
const iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const formatDate=d=>new Intl.DateTimeFormat('pt-BR',{day:'numeric',month:'long',year:'numeric'}).format(d);
const calendar=document.getElementById('calendar-days');
const prev=document.getElementById('prev-month');const next=document.getElementById('next-month');
const limitMonth=new Date(today.getFullYear(),today.getMonth()+12,1);
function renderCalendar(){document.getElementById('month-label').textContent=new Intl.DateTimeFormat('pt-BR',{month:'long',year:'numeric'}).format(month);calendar.replaceChildren();prev.disabled=month.getFullYear()===today.getFullYear()&&month.getMonth()===today.getMonth();next.disabled=month>=limitMonth;const first=month.getDay();const count=new Date(month.getFullYear(),month.getMonth()+1,0).getDate();for(let i=0;i<first;i++){let span=document.createElement('span');span.setAttribute('aria-hidden','true');calendar.append(span);}for(let day=1;day<=count;day++){const date=new Date(month.getFullYear(),month.getMonth(),day);const b=document.createElement('button');b.type='button';b.textContent=day;b.disabled=date<today;b.setAttribute('aria-label',formatDate(date));b.setAttribute('aria-pressed',String(selectedDate&&iso(selectedDate)===iso(date)||false));if(iso(date)===iso(today))b.classList.add('today');b.addEventListener('click',()=>{selectedDate=date;document.getElementById('date-summary').textContent='Sua preferência: '+formatDate(date);document.getElementById('form-error').hidden=true;document.getElementById('whatsapp-ready').hidden=true;renderCalendar();const selected=calendar.querySelector('[aria-pressed="true"]');selected?.focus({preventScroll:true});});calendar.append(b);}}
prev.addEventListener('click',()=>{month=new Date(month.getFullYear(),month.getMonth()-1,1);renderCalendar();});next.addEventListener('click',()=>{month=new Date(month.getFullYear(),month.getMonth()+1,1);renderCalendar();});renderCalendar();
document.querySelectorAll('[data-style]').forEach(b=>b.addEventListener('click',()=>{const radio=Array.from(document.querySelectorAll('input[name=style]')).find(r=>r.value===b.dataset.style);if(radio)radio.checked=true;document.getElementById('agendar').scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}));
const form=document.getElementById('booking-form');
form.addEventListener('input',()=>{document.getElementById('whatsapp-ready').hidden=true;});
form.addEventListener('submit',event=>{event.preventDefault();const error=document.getElementById('form-error');if(!selectedDate){error.textContent='Escolha uma data no calendário para solicitar seu atendimento.';error.hidden=false;calendar.querySelector('button:not(:disabled)')?.focus();return;}const name=document.getElementById('client-name').value.trim();const location=document.getElementById('location').value.trim();if(!name||!location){error.textContent='Informe seu nome e a cidade / bairro do atendimento.';error.hidden=false;document.getElementById(!name?'client-name':'location').focus();return;}error.hidden=true;const style=form.querySelector('input[name=style]:checked').value;const notes=document.getElementById('notes').value.trim();const text=`Oi, Julie! Vi suas tranças no site e queria marcar um horário. ♡\n\nNome: ${name}\nEstilo: ${style}\nData de preferência: ${formatDate(selectedDate)}\nPeríodo: ${document.getElementById('period').value}\nLocal: ${location}${notes?'\nMinha ideia: '+notes:''}\n\nVocê pode confirmar a disponibilidade e me passar o orçamento?`;const url='https://wa.me/5511910497848?text='+encodeURIComponent(text);const ready=document.getElementById('whatsapp-ready');ready.href=url;ready.hidden=false;window.open(url,'_blank','noopener,noreferrer');});
const galleryData={"g01": {"original": "assets/client-01.webp", "cover": "assets/portfolio-gold-1.webp", "alt": "Nagô lateral", "title": "Nagô lateral"}, "g06": {"original": "assets/client-06.webp", "cover": "assets/portfolio-gold-2.webp", "alt": "Nagô com volume natural", "title": "Nagô com volume natural"}, "g18": {"original": "assets/client-18.webp", "cover": "assets/portfolio-gold-3.webp", "alt": "Tranças longas de costas", "title": "Tranças longas de costas"}, "g16": {"original": "assets/client-16.webp", "cover": "assets/gold-g16.webp", "alt": "Tranças infantis", "title": "Tranças infantis"}, "g07": {"original": "assets/client-07.webp", "cover": "assets/gold-g07.webp", "alt": "Tranças com divisões delicadas", "title": "Tranças com divisões delicadas"}, "g14": {"original": "assets/client-14.webp", "cover": "assets/gold-g14.webp", "alt": "Nagô vista de cima", "title": "Nagô vista de cima"}, "g02": {"original": "assets/client-02.webp", "cover": "assets/gold-g02.webp", "alt": "Divisões na raiz", "title": "Divisões na raiz"}, "g04": {"original": "assets/client-04.webp", "cover": "assets/gold-g04.webp", "alt": "Nagô de frente", "title": "Nagô de frente"}, "g08": {"original": "assets/client-08.webp", "cover": "assets/gold-g08.webp", "alt": "Nagô lateral", "title": "Nagô lateral"}, "g09": {"original": "assets/client-09.webp", "cover": "assets/gold-g09.webp", "alt": "Nagô com cachos naturais", "title": "Nagô com cachos naturais"}, "g12": {"original": "assets/client-12.webp", "cover": "assets/gold-g12.webp", "alt": "Desenho na raiz", "title": "Desenho na raiz"}, "g17": {"original": "assets/client-17.webp", "cover": "assets/gold-g17.webp", "alt": "Nagô com tranças longas", "title": "Nagô com tranças longas"}};
const galleryKeys=Object.keys(galleryData);const dialog=document.getElementById('photo-dialog');let activePhoto=0;let showingOriginal=false;
function showPhoto(index){activePhoto=(index+galleryKeys.length)%galleryKeys.length;const photo=galleryData[galleryKeys[activePhoto]];const img=document.getElementById('dialog-image');img.src=showingOriginal?photo.original:photo.cover;img.alt=photo.alt;document.getElementById('photo-counter').textContent=`${activePhoto+1} / ${galleryKeys.length} · ${photo.title}`;const originalButton=document.getElementById('toggle-original');originalButton.hidden=photo.original===photo.cover;originalButton.textContent=showingOriginal?'Ver arte com contorno':'Ver foto original';const post=document.getElementById('post-link');post.hidden=!photo.post;if(photo.post)post.href=`https://www.instagram.com/julie_trancas_/p/${photo.post}/`;}
document.querySelectorAll('[data-photo]').forEach(b=>b.addEventListener('click',()=>{showingOriginal=false;showPhoto(galleryKeys.indexOf(b.dataset.photo));dialog.showModal();document.body.classList.add('modal-open');}));
document.getElementById('prev-photo').addEventListener('click',()=>{showingOriginal=false;showPhoto(activePhoto-1);});document.getElementById('next-photo').addEventListener('click',()=>{showingOriginal=false;showPhoto(activePhoto+1);});document.getElementById('toggle-original').addEventListener('click',()=>{showingOriginal=!showingOriginal;showPhoto(activePhoto);});
dialog.addEventListener('keydown',event=>{if(event.key==='ArrowLeft'){event.preventDefault();showingOriginal=false;showPhoto(activePhoto-1);}if(event.key==='ArrowRight'){event.preventDefault();showingOriginal=false;showPhoto(activePhoto+1);}});
const more=document.getElementById('gallery-more');more.addEventListener('click',()=>{const expanded=more.getAttribute('aria-expanded')==='true';document.querySelectorAll('.gallery-extra').forEach(card=>card.hidden=expanded);more.setAttribute('aria-expanded',String(!expanded));more.textContent=expanded?'Ver todas as 12 fotos':'Mostrar menos fotos';if(expanded)document.getElementById('galeria').scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});});
document.getElementById('close-photo').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>document.body.classList.remove('modal-open'));dialog.addEventListener('click',event=>{if(event.target===dialog){const rect=dialog.getBoundingClientRect();if(event.clientX<rect.left||event.clientX>rect.right||event.clientY<rect.top||event.clientY>rect.bottom)dialog.close();}});document.getElementById('photo-book').addEventListener('click',()=>dialog.close());document.getElementById('year').textContent=today.getFullYear();
